
spring:
    datasource :
        username : root
        password : rootpass
        url: jdbc:mysql://localhost:3306/course
        driver-class-name : com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
