
spring:
    datasourse:
        username : root
        password : rootpass
        url:jdbc:mysql://localhost:3306/sbms;
        Driver-class-name : com.mysql.jdbc.Drive


Jpa:
    Hibernate :
        Ddl-auto : update 
    Show-squl : true 